[phases.build]
# Build the Java backend using Maven
commands = [
  "cd backend",        # Ensure this matches your backend folder name
  "mvn clean install"   # Build the Java Spring Boot backend
]

[phases.start]
# Start the Java Spring Boot application
commands = [
  "java -jar backend/target/final-capstone-starter-1.0.jar"
]