[phases.build]
commands = [
  "cd backend",        # Navigate to the backend directory
  "mvn clean install"  # Build the backend with Maven
]

[phases.start]
commands = [
  "java -jar backend/target/final-capstone-starter-1.0.jar"  # Start the Spring Boot application
]
