[phases.build]
commands = [
  "apt-get update",              # Install Maven in the build phase
  "apt-get install -y maven",    # Ensure Maven is available
  "mvn clean install"            # Build the backend with Maven
]

#[phases.start]
#commands = [
#  "java -jar target/final-capstone-starter-1.0.jar"   # Start the backend application
#]
